### ISSUE TITLE
pid profile testing 2

### ISSUE THREAD

**Issue by cookie33** [EUDAT-B2SAFE/B2SAFE-core#80]
Hi,

It seems that testing the pid profile:
```
15:22 irodstest2.storage.sara.nl:/home/robertv/git/B2SAFE-core/scripts/tests 
robertv$ ./testB2SafeCmd.py -test b2safe
Test b2safe
Test : basic iRODS functions. ... ok
Test : put a file in iRODS ... ok
Test : search for non existing handles ... ok
Test : create a PID using b2safe (ror=None, fio=None, fixed_content=false) ... ok
Test : create a PID using b2safe (ror=pid,  fio=None, fixed_content=false) ... ok
Test : create a PID using b2safe (ror=None, fio=pid,  fixed_content=false) ... ok
Test : create a PID using b2safe (ror=None, fio=None, fixed_content=true) ... ok
Test : create a PID using b2safe (ror=pid,  fio=pid,  fixed_content=true) ... ok
Test : create a PID using b2safe (ror=841/test,  fio=841/test,  fixed_content=false) ... ok
Test : create PIDs for a collection and files using b2safe (fixed_content=false) ... ok
Test : create PIDs for a collection and files using b2safe (fixed_content=true) ... ok
Test : create PIDs for a collection and files using b2safe using similar directory names (fixed_content=false) ... ok
Test : create PIDs for a collection and files using b2safe using similar directory names (fixed_content=true) ... ok
Test : replicate a single file locally using b2safe (not registered, non recursive) ... FAIL
Test : replicate a single file locally using b2safe (not registered,     recursive) ... FAIL
Test : replicate a single file locally using b2safe (    registered, non recursive, ror=pid, fio=pid, fixed_content=false) ... ok
Test : replicate a single file locally using b2safe (    registered,     recursive, ror=pid, fio=pid, fixed_content=false) ... ok
Test : replicate a single directory locally using b2safe (not registered,    recursive) ... FAIL
Test : replicate a single directory locally using b2safe (    registered,    recursive, ror=pid, fio=pid, fixed_content=false) ... ok
Test : replicate multiple directories locally using b2safe (not registered,    recursive) ... FAIL
Test : replicate multiple directories locally using b2safe (    registered,    recursive, ror=pid, fio=pid, fixed_content=false) ... ok

======================================================================
FAIL: Test : replicate a single file locally using b2safe (not registered, non recursive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/robertv/git/B2SAFE-core/scripts/tests/testB2SafeCmd/irodsb2safetest.py", line 809, in test_70_b2safe_local_for_one_file_not_registered_non_recursive
    test_assert_array(self, test_values)
  File "/home/robertv/git/B2SAFE-core/scripts/tests/testB2SafeCmd/irodsb2safetest.py", line 56, in test_assert_array
    self.assertEqual(result, expected, output_string)
AssertionError: '' != '21.T12996/E81C56CA-1482-11E7-8A26-5254000DF0ED' : The FIO is NOT filled in in the replica in iCAT

======================================================================
FAIL: Test : replicate a single file locally using b2safe (not registered,     recursive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/robertv/git/B2SAFE-core/scripts/tests/testB2SafeCmd/irodsb2safetest.py", line 850, in test_70_b2safe_local_for_one_file_not_registered_recursive
    test_assert_array(self, test_values)
  File "/home/robertv/git/B2SAFE-core/scripts/tests/testB2SafeCmd/irodsb2safetest.py", line 56, in test_assert_array
    self.assertEqual(result, expected, output_string)
AssertionError: '' != '21.T12996/EA86D728-1482-11E7-B648-5254000DF0ED' : The PID of the original file is NOT the EUDAT/ROR value in the iCAT

======================================================================
FAIL: Test : replicate a single directory locally using b2safe (not registered,    recursive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/robertv/git/B2SAFE-core/scripts/tests/testB2SafeCmd/irodsb2safetest.py", line 1057, in test_75_b2safe_local_for_one_directory_not_registered_recursive
    test_assert_array(self, test_values)
  File "/home/robertv/git/B2SAFE-core/scripts/tests/testB2SafeCmd/irodsb2safetest.py", line 56, in test_assert_array
    self.assertEqual(result, expected, output_string)
AssertionError: '' != '21.T12996/fb9f3208-1482-11e7-b777-5254000df0ed' : The PID of the original file is NOT the EUDAT/ROR value in the iCAT

======================================================================
FAIL: Test : replicate multiple directories locally using b2safe (not registered,    recursive)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/robertv/git/B2SAFE-core/scripts/tests/testB2SafeCmd/irodsb2safetest.py", line 1232, in test_80_b2safe_local_for_multiple_directories_not_registered_recursive
    test_assert_array(self, test_values)
  File "/home/robertv/git/B2SAFE-core/scripts/tests/testB2SafeCmd/irodsb2safetest.py", line 56, in test_assert_array
    self.assertEqual(result, expected, output_string)
AssertionError: '' != '21.T12996/2162759A-1483-11E7-9F7B-5254000DF0ED' : The PID of the original file is NOT the EUDAT/ROR value in the iCAT

----------------------------------------------------------------------
Ran 21 tests in 208.065s

FAILED (failures=4)
```

This seems a bug. The FIO should be present in the replica. This happens when the original does NOT have a FIO filled in.

**Comment by cookie33** [comment]
it happens in the following function:
```
{*status = EUDATReplication(*source, *destination, *registered, *recursive, *response); if (*status) { writeLine('stdout', 'Success!'); } else { writeLine('stdout', 'Failed: *response'); }}
```
registered has to be set to false

**Comment by cookie33** [comment]
Well the function is:
```
EUDATReplication(*source, *destination, *registered, *recursive, *response) {

    logInfo("[EUDATReplication] transfering *source to *destination");
    *status = bool("true");
    *response = "";

    # Catch Error CAT_NO_ACCESS_PERMISSION before replication
    if (errormsg(EUDATCatchErrorDataOwner(*source,*msg), *errmsg) < 0) {

        logDebug("*errmsg");
        *status = bool("false");
        *response = "no access permission to the path *source for user $userNameClient";
        EUDATUpdateLogging(*status,*source,*destination,*response);

    } else {

        logInfo("[EUDATReplication] *msg");
        if (EUDATtoBoolean(*registered)) {
            logDebug("replicating registered data");
            *status = EUDATRegDataRepl(*source, *destination, EUDATtoBoolean(*recursive), *response);
        } else {
            logDebug("replicating data without PID registration");
            msiGetObjType(*source,*source_type);
            if (*source_type == '-c')  {
                msiCollRsync(*source,*destination,"null","IRODS_TO_IRODS",*rsyncStatus);
            }
            else if (*source_type == '-d') {
                msiDataObjRsync(*source,"IRODS_TO_IRODS","null",*destination,*rsyncStatus);
            }
            if (*rsyncStatus != 0) {
                logDebug("perform a further verification about checksum and size");
                *logEnabled = bool("true");
                *notification = 0;
                *status = EUDATCheckIntegrity(*source,*destination,*logEnabled,*notification,*response);
            }
        }
    }
```
So we should not expect anything. Because it only does an irods to irods rsync.

adapt check for better errors..
