### ISSUE TITLE
b2safe test command with iRODS 4.2

### ISSUE THREAD

**Issue by ccacciari** [EUDAT-B2SAFE/B2SAFE-core#86]
Executing the following command, with iRODS 4.2, using the test suite scripts/tests/testB2SafeCmd.py, I get:

```
$ ./testB2SafeCmd.py -test b2safe
[ ... ]
======================================================================
FAIL: test_10_irods_functions (testB2SafeCmd.irodsb2safetest.IrodsB2safeIntegrationTests)
Test : basic iRODS functions.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/irodsmaster/B2SAFE-core/scripts/tests/testB2SafeCmd/irodsb2safetest.py", line 244, in test_10_irods_functions
    test_assert_array(self, test_values)
  File "/home/irodsmaster/B2SAFE-core/scripts/tests/testB2SafeCmd/irodsb2safetest.py", line 56, in test_assert_array
    self.assertEqual(result, expected, output_string)
AssertionError: The username we expect is different

----------------------------------------------------------------------
Ran 25 tests in 519.245s

FAILED (failures=1)
```
this is due to a change in the output of the command _ienv_:
```
[ ... ]
irods_user_name - rods
[ ... ]
```
now the prefix _NOTICE_ does not appear anymore.

**Comment by cookie33** [comment]
It does following:
```
        irods_username_result = ''
        command = ["ienv"]
        ienv_result = subprocess_popen(command)
        for elem in ienv_result:
            if 'irods_user_name' in elem:
                irods_username_result = elem
        irods_username_result_expected = 'NOTICE: irods_user_name - '+self.irods_user_name

        # create array with values to test and execute
        test_values=[{ 'action': 'Equal', 'result_value': irods_username_result, 'expected_value': irods_username_result_expected, 'string': 'The username we expect is different'}]
        test_assert_array(self, test_values)
```

We can fix it as follows:
* make `irods_username_result = elem` without `NOTICE: `
* make the `irods_username_result_expected = 'irods_user_name - '+self.irods_user_name`

Than the test works for irods 4.1 and irods 4.2

**Comment by cookie33** [comment]
solution:
```
            irods_username_result=elem.strip("NOTICE: ")

irods_username_result_expected = 'irods_user_name - '+self.irods_user_name
```

**Comment by cookie33** [comment]
see #88 with a fix in the b2safe tests

**Comment by cookie33** [comment]
Merged and fixed in level branch

**Comment by cookie33** [comment]
Merged and fixed in level branch
